[project]
name = "hipertension-njs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jiehao", email = "jiehaoxu1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pathlib>=1.0.1",
    "requests>=2.34.2",
]

[tool.uv]
package = false
